/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validacion;

/**
 *
 * @author guevara
 */
public class Interface extends javax.swing.JFrame {

  
    Validacion Val=new Validacion();
    
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Validacion = new javax.swing.JButton();
        Entrada = new javax.swing.JTextField();
        SalidaNumeros = new javax.swing.JTextField();
        SalidaLetras = new javax.swing.JTextField();
        Confirmacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Validacion.setText("Validacion");
        Validacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidacionActionPerformed(evt);
            }
        });
        getContentPane().add(Validacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        getContentPane().add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, -1));
        getContentPane().add(SalidaNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));
        getContentPane().add(SalidaLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, -1));
        getContentPane().add(Confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidacionActionPerformed
        
        String cadena=Entrada.getText();
        Confirmacion.setText("");
        if(Val.isInteger(cadena.substring(2))){
        
            if(!Val.isInteger(cadena.substring(0, 1))){
            
                Confirmacion.setText("Formato valido");
            }else{
            
                Confirmacion.setText("Formato invalido");
            }
        }else{
        
            Confirmacion.setText("Formato invalido");
        }
    }//GEN-LAST:event_ValidacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirmacion;
    private javax.swing.JTextField Entrada;
    private javax.swing.JTextField SalidaLetras;
    private javax.swing.JTextField SalidaNumeros;
    private javax.swing.JButton Validacion;
    // End of variables declaration//GEN-END:variables
}
