/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guevara
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Numerostxt = new javax.swing.JTextField();
        Latrastxt = new javax.swing.JTextField();
        FiltroNumeros = new javax.swing.JTextField();
        FiltroLetras = new javax.swing.JTextField();
        Ejecutarbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Numerostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerostxtActionPerformed(evt);
            }
        });
        getContentPane().add(Numerostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 26, 95, -1));

        Latrastxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatrastxtActionPerformed(evt);
            }
        });
        getContentPane().add(Latrastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 26, 101, -1));
        getContentPane().add(FiltroNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 112, 95, -1));

        FiltroLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroLetrasActionPerformed(evt);
            }
        });
        getContentPane().add(FiltroLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 112, 101, -1));

        Ejecutarbtn.setText("Ejecutar");
        Ejecutarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Ejecutarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 177, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LatrastxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatrastxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatrastxtActionPerformed

    private void FiltroLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroLetrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroLetrasActionPerformed

    private void NumerostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerostxtActionPerformed

    private void EjecutarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EjecutarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejecutarbtn;
    private javax.swing.JTextField FiltroLetras;
    private javax.swing.JTextField FiltroNumeros;
    private javax.swing.JTextField Latrastxt;
    private javax.swing.JTextField Numerostxt;
    // End of variables declaration//GEN-END:variables
}
